detector:
  image_size: 224
  nms_threshold: 0.5
  conf_threshold: 0.5
  cpu: True
embedder:
  image_size: 112
  descriptor_size: &descriptor_size 512
  device: cpu
  architecture: iresnet100
database:
  descriptor_size: *descriptor_size