detector:
  image_size: 1000
  nms_threshold: 0.5
  conf_threshold: 0.5
  cpu: False
embedder:
  image_size: 112
  descriptor_size: &descriptor_size 512
  device: cpu
  architecture: iresnet34
database:
  descriptor_size: *descriptor_size