detector:
  image_size: 224
  nms_threshold: 0.5
  conf_threshold: 0.5
  device: cpu
  architecture: res50 # res50 (ResNet 50), mnet1 (mobilenet1)
embedder:
  image_size: 112
  descriptor_size: &descriptor_size 512
  device: cpu
  architecture: iresnet100
database:
  descriptor_size: *descriptor_size